### ISSUE TITLE
responses 类型报错

### ISSUE THREAD

**Issue by lynzz** [Cody2333/egg-swagger-decorator#2]
{
	"resource": "/Users/lzz/github/egg-ts-demo/app/controller/home.ts",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "类型“{ 200: { description: string; schema: { type: string; properties: { data: { type: string; example: string; }; }; }; }; }”的参数不能赋给类型“{ 200: { description: string; }; }”的参数。\n  属性“200”的类型不兼容。\n    不能将类型“{ description: string; schema: { type: string; properties: { data: { type: string; example: string; }; }; }; }”分配给类型“{ description: string; }”。\n      对象文字可以只指定已知属性，并且“schema”不在类型“{ description: string; }”中。",
	"source": "ts",
	"startLineNumber": 20,
	"startColumn": 7,
	"endLineNumber": 25,
	"endColumn": 8
}

仓库: [https://github.com/lynzz/egg-ts-demo](https://github.com/lynzz/egg-ts-demo)

可我看测试用例里是不会报这样的错，找不到原因，求解，谢谢

**Comment by Cody2333** [comment]
不好意思，最近比较忙，没怎么维护这个库。

这应该是个 bug， 这个问题在 koa-swgger-decorator 里面已经修复了，有空我会修复一下这个库中的问题。主要是缺少了 response 的类型声明， 有兴趣可以参考一下 koa-swagger-decorator 中的修改

https://github.com/Cody2333/koa-swagger-decorator/commit/1f4cadb41fc13915ca21887e0bf2fd946d7f7970

**Comment by lynzz** [comment]
谢谢，我去看看 @Cody2333

**Comment by Cody2333** [comment]
谢谢，已经合并发布了。
